### ISSUE TITLE
Investigate intermittent test failures

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/dropwizard-leader-latch#36]
We have seen a few test failures in `ManagedLeaderLatchCreatorTest` on recent builds. It is not always the same test, however the error seems to have the same cause:

```
Error:  Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.618 s <<< FAILURE! - in org.kiwiproject.curator.leader.ManagedLeaderLatchCreatorTest
Error:  org.kiwiproject.curator.leader.ManagedLeaderLatchCreatorTest.shouldNotRegisterResources_IfDisabled  Time elapsed: 0.023 s  <<< ERROR!
org.kiwiproject.curator.leader.exception.ManagedLeaderLatchException: Error starting leader latch
	at org.kiwiproject.curator.leader.ManagedLeaderLatchCreatorTest.shouldNotRegisterResources_IfDisabled(ManagedLeaderLatchCreatorTest.java:239)
Caused by: org.kiwiproject.curator.leader.exception.ManagedLeaderLatchException: Unable to create latch path: /kiwi/leader-latch/test-service/leader-latch
	at org.kiwiproject.curator.leader.ManagedLeaderLatchCreatorTest.shouldNotRegisterResources_IfDisabled(ManagedLeaderLatchCreatorTest.java:239)
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /kiwi/leader-latch/test-service/leader-latch
	at org.kiwiproject.curator.leader.ManagedLeaderLatchCreatorTest.shouldNotRegisterResources_IfDisabled(ManagedLeaderLatchCreatorTest.java:239)
```

See https://github.com/kiwiproject/dropwizard-leader-latch/runs/1407650945#step:6:2270

This doesn't make much sense since we have an `@AfterEach` method that deletes the node `/kiwi/leader-latch` _and all its child znodes_. Here is the current method:

```java
@AfterEach
void tearDown() throws Exception {
    var rootPath = "/kiwi/leader-latch";
    var stat = client.checkExists().forPath(rootPath);
    if (nonNull(stat)) {
        client.delete().deletingChildrenIfNeeded().forPath(rootPath);
    }
}
```
We did not see exceptions in the `tearDown` method, so maybe the `checkExists` call is failing? Or maybe the deletion silently fails? Or, although I think the delete call is _synchronous_, maybe it actually isn't?

**Comment by sleberknight** [comment]
Added to 0.15.0 because this problem is happening a lot when the CI build runs. For some reason this never happens when running locally on either macOS or Linux. Well, it has never happened to me, anyway...
